### ISSUE TITLE
Pls. add a secondary publishing destination

### ISSUE THREAD

**Issue by yvesio** [jbeyerstedt/kirby-widget-rsync_publishing#2]
Hi Jannik,

our usual web server setup consists of three servers:
- a password protected development server
- a password protected preview server – e.g. for discussions with the client
- a public live server

So it would be great to have such an option:

```
c::set('rsync_publishing.previewsite_folder', preview_site');
```

**Comment by jbeyerstedt** [comment]
OK, I will add an option to enable a second sync target.
