### ISSUE TITLE
Publishing to secondary site publishes to primary instead

### ISSUE THREAD

**Issue by yvesio** [jbeyerstedt/kirby-widget-rsync_publishing#5]
Hello Jannik,

I needed to reconfigure this widget since somebody deleted the config. As a first test I did a dry-run to the secondary site and then a real deployment to the secondary site. But surprisingly the deployment happened to the primary(!) site. It may be caused by these lines of code:

```
<?php if ($get_param == 'test' || $get_param == 'secondary_test') : ?>  

<div class="dashboard-box">  
  <a class="dashboard-item" href="<?php echo panel()->site()->url() ?>/panel?widget_rsyncpublishing=run">
```

To my (little) understanding you fire the same link independent if the user did a dry run to the primary or secondary site. So I tweaked the code above to this:

```
<?php if ($get_param == 'test') : ?>

<div class="dashboard-box">
  <a class="dashboard-item" href="<?php echo panel()->site()->url() ?>/panel?widget_rsyncpublishing=run">
    <figure>
      <span class="dashboard-item-icon dashboard-item-icon-with-border"><i class="fa fa-exchange"></i></span>
      <figcaption class="dashboard-item-text"><?php echo $strings[$lang]['butt_publish'] ?></figcaption>
    </figure>
  </a>
</div>
<div class="dashboard-box">
  <a class="dashboard-item" href="<?php echo panel()->site()->url() ?>/panel/">
    <figure>
      <span class="dashboard-item-icon dashboard-item-icon-with-border"><i class="fa fa-backward"></i></span>
      <figcaption class="dashboard-item-text"><?php echo $strings[$lang]['butt_abort'] ?></figcaption>
    </figure>
  </a>
</div>

<?php elseif ($get_param == 'secondary_test') : ?>

<div class="dashboard-box">
  <a class="dashboard-item" href="<?php echo panel()->site()->url() ?>/panel?widget_rsyncpublishing=secondary_run">
```

I am not familiar with Github and have too much respect for your code, so please feel free to incorporate it into your code if you think this makes sense.

Yours, Yves

**Comment by jbeyerstedt** [comment]
Your are absolutely right. Thank you for mentioning it here.

By the way: You don't have to be an expert with Github and my code is not that complicated. All the difficult stuff is handled by `rsync` and most of the lines of code are translation or assembling the bash script. All the html is just switching the different cases.

It should be fixed with the next commit.
